#!/usr/bin/env python3
"""
update-site-numbers.py: verify (and, for well-formed cases, rewrite) the
site's published pricing numbers against a single source of truth,
site-config.json.

This generalizes the marker-driven pattern used by
scripts/update-review-count.py, but pricing figures appear in far more
places, in far more sentence shapes, than the review-count trust line, and
wrapping every one of them in a new HTML comment marker would mean editing
hundreds of spots by hand first. So instead of a marker, this script is a
CHECKER-plus-REWRITER built on keyword anchors:

  * Every occurrence of a tier name ("Core Managed IT", "Secure Growth",
    "Compliance & Continuity" / "Compliance and Continuity", "Tiny Team" /
    "Tiny Team Managed Security") is an anchor.
  * For each anchor, the script looks at the text immediately around it
    (both directions) for the nearest dollar figure ($125, $175, ...) and
    treats that as the price the page is claiming for that tier at that
    spot.
  * A tier's onboarding fee is anchored the same way, but on "$1,000"'s
    context ("Tiny Team" + onboarding language) and on the "5 to 15 users"
    / "5-15 users" / "5<ndash>15 users" phrasing, GATED so it only fires
    when onboarding language ("onboarding", "scope", "one-time",
    "Microsoft 365 default") is nearby. Without that gate, "best for 5 to
    15 users" (the Core tier's headcount description, which sits next to
    the *tier* price, not an onboarding fee) would be misread as an
    onboarding-fee claim.
  * The site's JSON-LD Offer/priceSpecification blocks are also checked,
    by reading the "price" field nearest to (and following) each Offer's
    "name" field.
  * assets/js/pricing.js's TIER_PRICES object is checked the same way, but
    is never rewritten by this script (see USAGE).

USAGE
-----
    python update-site-numbers.py --root /path/to/ghosxt --check   (default)
    python update-site-numbers.py --root /path/to/ghosxt --apply
    python update-site-numbers.py --root /path/to/ghosxt --config my-config.json --check

Modes
-----
  --check (default, and what a bare invocation with no flags does): scans
    root *.html and blog/*.html for dollar figures anchored to tier names,
    and reports:
      - MISMATCH: a confidently-anchored dollar figure that does not equal
        the config value for that tier/fee.
      - low-confidence note: a figure found only via a long-distance
        anchor (e.g. a "choose this tier if..." card where the price sits
        a paragraph after the tier name). Reported for visibility, not
        counted as a failure, since it is not eligible for --apply anyway.
      - ignored: recognized non-Ghosxt-price context sitting near a tier
        keyword purely by coincidence (e.g. the Core tier's "best for 5 to
        15 users" headcount blurb, which is not an onboarding-fee claim).
    It also reports assets/js/pricing.js TIER_PRICES mismatches (report
    only, never rewritten by this script: pricing.js's minified sibling is
    regenerated by scripts/minify.py --refs, a separate step).
  --apply: rewrites only the confidently-anchored (short-distance) dollar
    figures identified above that do not match the config, leaving every
    low-confidence or ignored figure untouched. Never touches
    assets/js/pricing.js or JSON-LD price fields (report-only, see above).
    Without --apply the script ALWAYS runs as a dry run/check.

Notes
-----
  * Idempotent: once every figure matches the config, both modes report
    zero mismatches and --apply (if run) rewrites nothing.
  * This script deliberately does not touch prose that mentions dollar
    figures with no tier name nearby (market-rate ranges like "$25 to $45
    per user per month" for MDR, Microsoft 365 license prices like "$22
    per user per month", or web-design project prices like "$1,800
    Essential"): those are outside the scope of "dollar figures adjacent
    to tier names" and are correctly never treated as anchors in the
    first place.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

EXCLUDE_DIR_NAMES = {".git", "assets", "node_modules"}

# How far (in characters) an anchor may look for a dollar figure before
# giving up. STRICT_CHARS is the "confident, apply-eligible" radius seen
# in the vast majority of same-line/same-sentence occurrences (badges,
# aria-labels, FAQ prose, plan tables). WIDE_CHARS additionally covers the
# handful of "choose this tier if..." cards where a paragraph of body copy
# sits between the tier name heading and its price line; matches only
# found at WIDE_CHARS distance are reported for visibility but are never
# rewritten by --apply.
STRICT_CHARS = 90
WIDE_CHARS = 480

## \d{1,3}(?:,\d{3})* requires each comma to be followed by a full group of
## three digits (proper thousands separators), so a trailing sentence comma
## right after the figure ("Secure Growth is $175, and...") is never pulled
## into the match the way a bare [\d,]+ character class would pull it in.
DOLLAR_RE = re.compile(r"\$(\d{1,3}(?:,\d{3})*)(?:\.\d+)?")

# A candidate dollar figure is rejected (not treated as belonging to the
# anchor under consideration) if the text strictly between the anchor and
# the figure contains any of these boundary signals. These were derived
# empirically from the real false-positive patterns in this corpus:
#   - another tier name sitting in between (e.g. a "choose this tier if..."
#     card whose *own* price is a full paragraph away, but the *previous*
#     card's tier name + price is only a few words away)
#   - a sentence boundary ("...24/7 SOC layer. Best for...")
#   - a list-item boundary (each <li> is its own independent fact/claim)
#   - "everything in <tier>" / "in addition to <tier>" cross-references,
#     which name a tier for comparison without giving it a price
#   - a JSON-LD object boundary ("@type") between adjacent Offer entries
#   - a "$X to $Y" / "$X-$Y" market-range figure (the range as a whole is
#     the claim, not either endpoint individually)
#   - a structural block boundary (</article>, or the pricing calculator's
#     "compare-row" widget rows), which each hold one independent fact
# A short, comma-led connector ("Core Managed IT, $175 for Secure Growth")
# is also rejected: it means "here comes the next item in the list", not
# "here is this item's own value" (contrast "Core Managed IT tier, $125",
# where the comma is preceded by real words, not by the anchor itself).
BARE_LIST_SEPARATOR_RE = re.compile(r"^\s*,")
BARE_LIST_SEPARATOR_MAX_LEN = 20
SENTENCE_BOUNDARY_RE = re.compile(r"\.\s")
STRUCTURAL_BOUNDARY_RE = re.compile(r"</li>|<li[\s>]|</article>|compare-row|compare-value")
CROSS_REFERENCE_RE = re.compile(r"everything in|in addition to", re.IGNORECASE)
JSON_OBJECT_BOUNDARY_RE = re.compile(r'"@type"')
RANGE_BEFORE_RE = re.compile(r"\$[\d,]+\s*(?:to|-|–)\s*$")
RANGE_AFTER_RE = re.compile(r"^\s*(?:to|-|–)\s*\$[\d,]+")


def connector_is_valid(connector: str, anchor_res) -> bool:
    """Return False if the text between an anchor and a dollar-figure
    candidate contains a boundary signal that means the two do not
    actually belong together (see comment above)."""
    if BARE_LIST_SEPARATOR_RE.match(connector) and len(connector) <= BARE_LIST_SEPARATOR_MAX_LEN:
        return False
    if SENTENCE_BOUNDARY_RE.search(connector):
        return False
    if STRUCTURAL_BOUNDARY_RE.search(connector):
        return False
    if CROSS_REFERENCE_RE.search(connector):
        return False
    if JSON_OBJECT_BOUNDARY_RE.search(connector):
        return False
    for anchor_re in anchor_res:
        if anchor_re.search(connector):
            return False
    return True


def is_range_member(text: str, span: Tuple[int, int]) -> bool:
    """True if the dollar figure at `span` is one end of a "$X to $Y" /
    "$X-$Y" market-range mention, and therefore not a standalone claim
    that can be pinned to any single tier."""
    before = text[max(0, span[0] - 12):span[0]]
    after = text[span[1]:span[1] + 12]
    return bool(RANGE_BEFORE_RE.search(before) or RANGE_AFTER_RE.search(after))


TIER_ANCHORS: Dict[str, re.Pattern] = {
    "Core Managed IT": re.compile(r"Core Managed IT(?:\s+Services)?"),
    "Secure Growth": re.compile(r"Secure Growth(?:\s+Managed IT Services)?"),
    "Compliance & Continuity": re.compile(
        r"Compliance\s*(?:&|&amp;|and)\s*Continuity(?:\s+Managed IT Services)?"
    ),
    "Tiny Team": re.compile(r"Tiny Team(?:\s+Managed Security)?"),
}

# The onboarding "5 to 15 users" tier only ever appears as a genuine
# onboarding-fee claim when onboarding language is nearby; the same phrase
# also shows up as the Core tier's headcount blurb next to the *tier*
# price ("Core Managed IT tier, $125 per user per month, best for 5 to 15
# users"), which is not an onboarding fee and must not be treated as one.
FIVE_TO_FIFTEEN_RE = re.compile(r"5\s*(?:to|[-–])\s*15\s*users")
ONBOARDING_CONTEXT_RE = re.compile(
    r"onboarding|scope|one-time|Microsoft 365 default", re.IGNORECASE
)
ONBOARDING_CONTEXT_WINDOW = 320

# "Tiny Team" needs the same onboarding-language gate as "5 to 15 users"
# (see above), but a much tighter window: "Tiny Team" is common enough in
# marketing copy that a 320-char radius reliably catches an unrelated
# "one-time assessments" or "...scope for what is included at every tier"
# mention several sentences later and wrongly treats an ordinary monthly-
# rate sentence as an onboarding-fee claim. Every real onboarding-fee
# mention of "Tiny Team" in this corpus has the onboarding language within
# a few words either side (e.g. "Tiny Team onboarding", "onboarding of
# $1,000 flat for a Tiny Team"); this window is sized for that, not for a
# whole paragraph.
TINY_TEAM_ONBOARDING_CONTEXT_WINDOW = 80

# JSON-LD Offer names that map to a tier/fee config key.
JSON_OFFER_NAME_TO_CONFIG_KEY = {
    "tiny team managed security": "tiny_team_monthly",
    "core managed it": "core_per_user",
    "core managed it services": "core_per_user",
    "secure growth": "secure_growth_per_user",
    "secure growth managed it services": "secure_growth_per_user",
    "compliance & continuity": "compliance_continuity_per_user",
    "compliance and continuity": "compliance_continuity_per_user",
    "compliance & continuity managed it services": "compliance_continuity_per_user",
}

JSON_NAME_RE = re.compile(r'"name":\s*"([^"]+)"')
JSON_PRICE_RE = re.compile(r'"price":\s*"(\d+)"')
JSON_MAX_NAME_DISTANCE = 700

PRICING_JS_RE = re.compile(r"const\s+TIER_PRICES\s*=\s*\{([^}]*)\}")
PRICING_JS_ENTRY_RE = re.compile(r"(\w+)\s*:\s*(\d+)")
PRICING_JS_TIER_TO_CONFIG_KEY = {
    "essential": "core_per_user",
    "professional": "secure_growth_per_user",
    "premium": "compliance_continuity_per_user",
}


def parse_money(raw: str) -> int:
    return int(raw.replace(",", ""))


def fmt_money(n: int) -> str:
    return f"{n:,}"


def line_no(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def snippet(text: str, start: int, end: int, pad: int = 30) -> str:
    s = max(0, start - pad)
    e = min(len(text), end + pad)
    return text[s:e].replace("\n", " ").strip()


@dataclass
class Finding:
    file: str
    line: int
    anchor: str
    expected: str
    found: int
    span: Tuple[int, int]
    confident: bool
    context: str
    status: str  # "ok", "mismatch", "ignored"
    note: str = ""


def span_distance(a: Tuple[int, int], b: Tuple[int, int]) -> int:
    if a[1] <= b[0]:
        return b[0] - a[1]
    if b[1] <= a[0]:
        return a[0] - b[1]
    return 0  # overlapping


def has_closer_owner(
    candidate_span: Tuple[int, int],
    own_anchor_span: Tuple[int, int],
    own_distance: int,
    all_anchor_spans: List[Tuple[int, int]],
) -> bool:
    """True if some *other* tier-name occurrence in the file sits closer to
    this dollar figure than the anchor currently being evaluated does, i.e.
    the figure more plausibly belongs to that other occurrence."""
    for span in all_anchor_spans:
        if span == own_anchor_span:
            continue
        if span_distance(candidate_span, span) < own_distance:
            return True
    return False


def nearest_dollar(
    text: str,
    anchor_start: int,
    anchor_end: int,
    cap: int,
    anchor_res=(),
    all_anchor_spans: Optional[List[Tuple[int, int]]] = None,
):
    """Return (value, match_span, distance) for the dollar figure nearest
    to the anchor within `cap` characters on either side, or None.

    Candidates are checked closest-first in each direction; a candidate is
    skipped (not just deprioritized) if the text between it and the anchor
    fails connector_is_valid (see that function's docstring for why), if it
    is one end of a "$X to $Y" range, or if some other tier-name occurrence
    in the file sits closer to it (has_closer_owner)."""
    own_span = (anchor_start, anchor_end)
    all_anchor_spans = all_anchor_spans or []
    best = None  # (distance, value, span)

    # forward: walk candidates nearest-first, skip invalid connectors
    window_end = min(len(text), anchor_end + cap)
    fwd_text = text[anchor_end:window_end]
    for m in DOLLAR_RE.finditer(fwd_text):
        connector = fwd_text[:m.start()]
        if not connector_is_valid(connector, anchor_res):
            continue
        span = (anchor_end + m.start(), anchor_end + m.end())
        if is_range_member(text, span):
            continue
        dist = m.start()
        if has_closer_owner(span, own_span, dist, all_anchor_spans):
            continue
        best = (dist, parse_money(m.group(1)), span)
        break

    # backward: walk candidates nearest-first (i.e. from the end of the
    # backward window toward the anchor), skip invalid connectors
    window_start = max(0, anchor_start - cap)
    back_text = text[window_start:anchor_start]
    for m in reversed(list(DOLLAR_RE.finditer(back_text))):
        connector = back_text[m.end():]
        if not connector_is_valid(connector, anchor_res):
            continue
        span = (window_start + m.start(), window_start + m.end())
        if is_range_member(text, span):
            continue
        dist = len(back_text) - m.end()
        if has_closer_owner(span, own_span, dist, all_anchor_spans):
            continue
        if best is None or dist < best[0]:
            best = (dist, parse_money(m.group(1)), span)
        break

    if best is None:
        return None
    dist, value, span = best
    return value, span, dist


def scan_tier_prices(path: str, rel: str, text: str, pricing: dict) -> List[Finding]:
    findings: List[Finding] = []
    tier_to_key = {
        "Core Managed IT": "core_per_user",
        "Secure Growth": "secure_growth_per_user",
        "Compliance & Continuity": "compliance_continuity_per_user",
        # "Tiny Team" is handled separately below: it is legitimately near
        # two different real values (its flat monthly rate, or its
        # onboarding fee) depending on context, so it needs the same
        # onboarding-language gate as the "5 to 15 users" anchor rather
        # than an "accept either value" rule (accepting either made
        # --apply rewrite a genuine mismatch to the wrong one of the two
        # whenever the nearby text was actually an onboarding-fee claim).
    }

    anchor_res = list(TIER_ANCHORS.values())
    all_anchor_spans = [m.span() for anchor_re in anchor_res for m in anchor_re.finditer(text)]

    for label, config_key in tier_to_key.items():
        anchor_re = TIER_ANCHORS[label]
        expected_value = pricing[config_key]

        for m in anchor_re.finditer(text):
            result = nearest_dollar(text, m.start(), m.end(), STRICT_CHARS, anchor_res, all_anchor_spans)
            confident = True
            if result is None:
                result = nearest_dollar(text, m.start(), m.end(), WIDE_CHARS, anchor_res, all_anchor_spans)
                confident = False
            if result is None:
                continue
            value, span, dist = result

            status = "ok" if value == expected_value else "mismatch"
            findings.append(
                Finding(
                    file=rel,
                    line=line_no(text, m.start()),
                    anchor=label,
                    expected=f"${fmt_money(expected_value)}",
                    found=value,
                    span=span,
                    confident=confident,
                    context=snippet(text, min(m.start(), span[0]), max(m.end(), span[1])),
                    status=status,
                )
            )

    # Tiny Team: gated on nearby onboarding language exactly like the
    # "5 to 15 users" anchor below, so each occurrence is checked (and, if
    # a mismatch, rewritten by --apply) against the single value that
    # actually applies there, instead of silently accepting whichever of
    # the two real values happened to be present.
    tiny_re = TIER_ANCHORS["Tiny Team"]
    for m in tiny_re.finditer(text):
        ctx_start = max(0, m.start() - TINY_TEAM_ONBOARDING_CONTEXT_WINDOW)
        ctx_end = min(len(text), m.end() + TINY_TEAM_ONBOARDING_CONTEXT_WINDOW)
        is_onboarding = bool(ONBOARDING_CONTEXT_RE.search(text[ctx_start:ctx_end]))
        matched_key = "onboarding_tiny_team" if is_onboarding else "tiny_team_monthly"
        expected_value = pricing[matched_key]

        result = nearest_dollar(text, m.start(), m.end(), STRICT_CHARS, anchor_res, all_anchor_spans)
        confident = True
        if result is None:
            result = nearest_dollar(text, m.start(), m.end(), WIDE_CHARS, anchor_res, all_anchor_spans)
            confident = False
        if result is None:
            continue
        value, span, dist = result

        status = "ok" if value == expected_value else "mismatch"
        findings.append(
            Finding(
                file=rel,
                line=line_no(text, m.start()),
                anchor=f"Tiny Team ({matched_key})",
                expected=f"${fmt_money(expected_value)}",
                found=value,
                span=span,
                confident=confident,
                context=snippet(text, min(m.start(), span[0]), max(m.end(), span[1])),
                status=status,
            )
        )

    # Onboarding: 5-to-15-users fee, gated on nearby onboarding language.
    expected_5_15 = pricing["onboarding_5_to_15"]
    for m in FIVE_TO_FIFTEEN_RE.finditer(text):
        ctx_start = max(0, m.start() - ONBOARDING_CONTEXT_WINDOW)
        ctx_end = min(len(text), m.end() + ONBOARDING_CONTEXT_WINDOW)
        if not ONBOARDING_CONTEXT_RE.search(text[ctx_start:ctx_end]):
            findings.append(
                Finding(
                    file=rel,
                    line=line_no(text, m.start()),
                    anchor="5 to 15 users (no onboarding context)",
                    expected="n/a",
                    found=-1,
                    span=(m.start(), m.end()),
                    confident=True,
                    context=snippet(text, m.start(), m.end()),
                    status="ignored",
                    note="tier headcount blurb, not an onboarding-fee claim",
                )
            )
            continue

        result = nearest_dollar(text, m.start(), m.end(), STRICT_CHARS, anchor_res, all_anchor_spans)
        confident = True
        if result is None:
            result = nearest_dollar(text, m.start(), m.end(), WIDE_CHARS, anchor_res, all_anchor_spans)
            confident = False
        if result is None:
            continue
        value, span, dist = result
        status = "ok" if value == expected_5_15 else "mismatch"
        findings.append(
            Finding(
                file=rel,
                line=line_no(text, m.start()),
                anchor="onboarding: 5 to 15 users",
                expected=f"${fmt_money(expected_5_15)}",
                found=value,
                span=span,
                confident=confident,
                context=snippet(text, min(m.start(), span[0]), max(m.end(), span[1])),
                status=status,
            )
        )

    return findings


def scan_json_ld(rel: str, text: str, pricing: dict) -> Tuple[List[Finding], int]:
    findings: List[Finding] = []
    ignored_count = 0
    names = list(JSON_NAME_RE.finditer(text))

    def nearest_preceding_name(pos: int):
        best = None
        for nm in names:
            if nm.start() >= pos:
                break
            if pos - nm.end() > JSON_MAX_NAME_DISTANCE:
                continue
            best = nm
        return best

    for pm in JSON_PRICE_RE.finditer(text):
        nm = nearest_preceding_name(pm.start())
        if nm is None:
            continue
        name_norm = nm.group(1).replace("&amp;", "&").strip().lower()
        config_key = JSON_OFFER_NAME_TO_CONFIG_KEY.get(name_norm)
        if config_key is None:
            ignored_count += 1
            continue
        expected = pricing[config_key]
        found = int(pm.group(1))
        status = "ok" if found == expected else "mismatch"
        findings.append(
            Finding(
                file=rel,
                line=line_no(text, pm.start()),
                anchor=f'JSON-LD "{nm.group(1)}"',
                expected=f"${fmt_money(expected)}",
                found=found,
                span=pm.span(1),
                confident=True,
                context=snippet(text, nm.start(), pm.end()),
                status=status,
            )
        )
    return findings, ignored_count


def scan_pricing_js(path: str, pricing: dict) -> List[Finding]:
    findings: List[Finding] = []
    if not os.path.isfile(path):
        return findings
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    m = PRICING_JS_RE.search(text)
    if not m:
        return findings
    for entry in PRICING_JS_ENTRY_RE.finditer(m.group(1)):
        tier, value = entry.group(1), int(entry.group(2))
        config_key = PRICING_JS_TIER_TO_CONFIG_KEY.get(tier)
        if config_key is None:
            continue
        expected = pricing[config_key]
        status = "ok" if value == expected else "mismatch"
        findings.append(
            Finding(
                file=os.path.relpath(path, os.path.dirname(os.path.dirname(path))),
                line=line_no(text, entry.start()),
                anchor=f"pricing.js TIER_PRICES.{tier}",
                expected=f"${fmt_money(expected)}",
                found=value,
                span=entry.span(2),
                confident=True,
                context=snippet(text, m.start(), m.end()),
                status=status,
            )
        )
    return findings


def discover_html_files(root: str) -> List[str]:
    found = []
    for name in os.listdir(root):
        if name.endswith(".html"):
            found.append(name)
    blog_dir = os.path.join(root, "blog")
    if os.path.isdir(blog_dir):
        for name in os.listdir(blog_dir):
            if name.endswith(".html"):
                found.append(os.path.join("blog", name))
    return sorted(found)


def apply_rewrites(path: str, text: str, findings: List[Finding]) -> Tuple[str, int]:
    """Rewrite only confident mismatches, from the end of the file backward
    so earlier spans stay valid while later ones are replaced."""
    to_fix = [f for f in findings if f.status == "mismatch" and f.confident and f.found >= 0]
    to_fix.sort(key=lambda f: f.span[0], reverse=True)
    changed = 0
    for f in to_fix:
        # Recover the expected numeric value from the (possibly "$X or $Y")
        # description: rewriting always targets the primary tier value,
        # i.e. the first one listed.
        first = f.expected.split(" or ")[0].lstrip("$").replace(",", "")
        new_value = "$" + fmt_money(int(first))
        start, end = f.span
        old_value = text[start:end]
        # f.span always comes from a DOLLAR_RE match (the whole "$NNN"
        # token, not just the digits), so the text being replaced must
        # start with the dollar sign. If it doesn't, something upstream
        # handed us a digits-only span (e.g. a JSON-LD or pricing.js
        # finding, which this function must never receive), and writing
        # the file would silently drop the "$" from a real price.
        assert old_value.startswith("$"), (
            f"refusing to rewrite {f.file}:{f.line} ({f.anchor}): "
            f"span {f.span} = {old_value!r} does not start with '$'"
        )
        text = text[:start] + new_value + text[end:]
        changed += 1
    return text, changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=".", help="Path to the ghosxt repo root (default: current directory).")
    parser.add_argument("--config", default=None, help="Path to the config JSON (default: site-config.json in the repo root).")
    parser.add_argument("--apply", action="store_true", help="Rewrite confidently-anchored mismatches. Without this flag the script ALWAYS runs as a check/dry run.")
    parser.add_argument("--check", action="store_true", help="Explicit check flag (informational only; this is the default).")
    parser.add_argument("-v", "--verbose", action="store_true", help="Also print every OK match, not just mismatches/ignored items.")
    args = parser.parse_args()

    root = os.path.abspath(args.root)
    if not os.path.isdir(root):
        print(f"error: --root {root!r} is not a directory", file=sys.stderr)
        return 2

    config_path = args.config or os.path.join(root, "site-config.json")
    if not os.path.isfile(config_path):
        print(f"error: config file not found: {config_path}", file=sys.stderr)
        return 2
    with open(config_path, "r", encoding="utf-8") as f:
        config = json.load(f)
    pricing = config["pricing"]

    apply_changes = args.apply
    html_files = discover_html_files(root)

    print("=" * 78)
    print(f"update-site-numbers.py: {'APPLY' if apply_changes else 'CHECK (dry run)'}")
    print(f"root: {root}")
    print(f"config: {config_path}")
    print(
        "pricing: Tiny Team ${tt}/mo, Core ${c}/user/mo, Secure Growth ${sg}/user/mo, "
        "Compliance & Continuity ${cc}/user/mo, onboarding ${ot} (Tiny Team) / ${o515} (5-15 users)".format(
            tt=fmt_money(pricing["tiny_team_monthly"]),
            c=fmt_money(pricing["core_per_user"]),
            sg=fmt_money(pricing["secure_growth_per_user"]),
            cc=fmt_money(pricing["compliance_continuity_per_user"]),
            ot=fmt_money(pricing["onboarding_tiny_team"]),
            o515=fmt_money(pricing["onboarding_5_to_15"]),
        )
    )
    print(f"html files scanned: {len(html_files)} (root *.html + blog/*.html)")
    print("=" * 78)

    total_ok = 0
    total_ok_wide = 0
    total_mismatch = 0
    total_ignored = 0
    total_json_ok = 0
    total_json_mismatch = 0
    total_json_ignored = 0
    files_rewritten = 0
    fields_rewritten = 0

    for rel in html_files:
        path = os.path.join(root, rel)
        with open(path, "r", encoding="utf-8") as f:
            original = f.read()

        findings = scan_tier_prices(path, rel, original, pricing)
        json_findings, json_ignored = scan_json_ld(rel, original, pricing)
        total_json_ignored += json_ignored

        interesting = [
            f for f in findings
            if f.status != "ok" or not f.confident or args.verbose
        ]
        for f in interesting:
            if f.status == "ok":
                tag = "ok (long-distance match)"
            elif f.status == "ignored":
                tag = f"ignored ({f.note})"
            else:
                tag = "MISMATCH"
            print(f"  [{tag}] {f.file}:{f.line}  {f.anchor} -> expected {f.expected}, found ${fmt_money(f.found) if f.found >= 0 else 'n/a'}")
            print(f"      ...{f.context}...")

        for f in findings:
            if f.status == "ok":
                total_ok += 1 if f.confident else 0
                total_ok_wide += 0 if f.confident else 1
            elif f.status == "mismatch":
                total_mismatch += 1
            elif f.status == "ignored":
                total_ignored += 1

        for f in json_findings:
            if f.status == "ok":
                total_json_ok += 1
            else:
                total_json_mismatch += 1
                print(f"  [MISMATCH] {f.file}:{f.line}  {f.anchor} -> expected {f.expected}, found ${fmt_money(f.found)}")
                print(f"      ...{f.context}...")

        if apply_changes:
            new_text, n = apply_rewrites(path, original, findings)
            if n:
                fields_rewritten += n
                files_rewritten += 1
                with open(path, "w", encoding="utf-8") as f:
                    f.write(new_text)

    # assets/js/pricing.js: report only, never rewritten here.
    pricing_js_path = os.path.join(root, "assets", "js", "pricing.js")
    js_findings = scan_pricing_js(pricing_js_path, pricing)
    js_mismatch = 0
    for f in js_findings:
        if f.status != "ok":
            js_mismatch += 1
            print(f"  [MISMATCH] assets/js/pricing.js:{f.line}  {f.anchor} -> expected {f.expected}, found ${fmt_money(f.found)}")
            print(f"      ...{f.context}...")
        elif args.verbose:
            print(f"  [ok] assets/js/pricing.js:{f.line}  {f.anchor} -> {f.expected}")

    print("-" * 78)
    print(
        f"tier/onboarding anchors: {total_ok} ok, {total_ok_wide} ok (long-distance), "
        f"{total_mismatch} MISMATCH, {total_ignored} ignored (non-onboarding context)"
    )
    print(
        f"JSON-LD Offer prices: {total_json_ok} ok, {total_json_mismatch} MISMATCH, "
        f"{total_json_ignored} ignored (non-tier offers, e.g. website-development.html packages)"
    )
    print(f"assets/js/pricing.js TIER_PRICES: {len(js_findings) - js_mismatch} ok, {js_mismatch} MISMATCH (report only, never rewritten)")
    if apply_changes:
        print(f"files rewritten: {files_rewritten}   fields rewritten: {fields_rewritten}")
    print("=" * 78)

    hard_failures = total_mismatch + total_json_mismatch + js_mismatch
    if hard_failures:
        print(f"RESULT: {hard_failures} mismatch(es) found against site-config.json pricing.")
        return 1
    print("RESULT: no mismatches. Every tier/onboarding price checked matches site-config.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
